name: Publish Crate

on:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  test-and-publish:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Git
        run: |
          git config --global user.name "release-bot"
          git config --global user.email "release-bot@github.com"

      - name: Set up Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true

      - name: Run cargo check
        run: cargo check

      - name: Run cargo test
        run: cargo test

      - name: Install cargo-release
        run: cargo install cargo-release

      - name: Bump version and publish
        run: cargo release patch --no-verify --no-confirm --execute
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          CARGO_REGISTRY_TOKEN: ${{ secrets.CARGO_REGISTRY_TOKEN }}


